# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  hardware.enableRedistributableFirmware = true;

  boot = {
    kernelModules = [
      "kvm-amd"
      "lm75" # temperature sensors
      "nct6775" # temperature sensors
    ];
    kernelParams = [
      "nvidia-drm.fbdev=1" # disable additional dummy display
      "nvidia.NVreg_EnableGpuFirmware=0" # https://github.com/NVIDIA/open-gpu-kernel-modules/issues/538
    ];
    loader = {
      systemd-boot.enable = true;
      systemd-boot.consoleMode = "auto";
      efi.canTouchEfiVariables = true;
    };
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
      luks.devices = {
        "root" = {
          device = "/dev/disk/by-uuid/e0a78f05-e0b6-4fbb-bf07-08b432b291d5";
          allowDiscards = true;
          bypassWorkqueues = true;
        };
      };
    };
  };

  environment.etc.crypttab.text = ''
    hdd PARTLABEL=HDD /etc/keyfile/hdd.key nofail
    ssd PARTLABEL=SSD /etc/keyfile/ssd.key allow-discards,no-read-workqueue,no-write-workqueue
  '';

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=25%" "mode=755" ];
    };
    "/nix" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "defaults" "compress=zstd" "discard=async" "subvol=@nix" ];
      neededForBoot = true;
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/FC4D-3317";
      fsType = "vfat";
    };
    "/.fsroot" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "defaults" "compress=zstd" "discard=async" ];
    };
    "/home" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [ "defaults" "compress=zstd" "discard=async" "subvol=@home" ];
    };
    "/mnt/extra" = {
      device = "/dev/mapper/ssd";
      fsType = "btrfs";
      options = [ "defaults" "compress=zstd" "discard=async" "subvol=@user" ];
    };
    "/mnt/extra/.fsroot" = {
      device = "/dev/mapper/ssd";
      fsType = "btrfs";
      options = [ "defaults" "compress=zstd" "discard=async" ];
    };
    "/mnt/hdd" = {
      device = "/dev/mapper/hdd";
      fsType = "btrfs";
      options = [ "defaults" "compress=zstd" "autodefrag" "subvol=@user" ];
    };
    "/mnt/hdd/.fsroot" = {
      device = "/dev/mapper/hdd";
      fsType = "btrfs";
      options = [ "defaults" "compress=zstd" "autodefrag" ];
    };
    "/mnt/tmp" = {
      device = "tmpfs";
      fsType = "tmpfs";
      options = [ "rw" "noexec" "nodev" "nosuid" "uid=1000" "gid=1000" "mode=1700" ];
    };
  };


  networking.hostName = "DESKTOP-IJK2GUG";
  networking.networkmanager.enable = true;

  nixpkgs.hostPlatform = "x86_64-linux";

  # Enable OpenGL
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;

  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = ["nvidia"];

  hardware.nvidia = {

    # Modesetting is required.
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    # Enable this if you have graphical corruption issues or application crashes after waking
    # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead
    # of just the bare essentials.
    powerManagement.enable = true;

    # Fine-grained power management. Turns off GPU when not in use.
    # Experimental and only works on modern Nvidia GPUs (Turing or newer).
    powerManagement.finegrained = false;

    # Use the NVidia open source kernel module (not to be confused with the
    # independent third-party "nouveau" open source driver).
    # Support is limited to the Turing and later architectures. Full list of
    # supported GPUs is at:
    # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
    # Only available from driver 515.43.04+
    # Currently alpha-quality/buggy, so false is currently the recommended setting.
    open = false;

    # Enable the Nvidia settings menu,
	  # accessible via `nvidia-settings`.
    nvidiaSettings = true;

    # Optionally, you may need to select the appropriate driver version for your specific GPU.
    # https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/nvidia-x11/default.nix
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  hardware.nvidia-container-toolkit.enable = true;
  services.ollama.acceleration = "cuda";

  nixpkgs.allowedUnfreePackages = [
    "nvidia-x11" "nvidia-settings" "nvidia-persistenced" # drivers
    "cuda_nvcc" "cuda_cudart" "libcublas" "cuda_cccl" # ollama
  ];

  boot.extraModprobeConfig = ''
    options nvidia NVreg_TemporaryFilePath=/var/tmp
  '';

  hardware.cpu.amd.updateMicrocode = config.hardware.enableRedistributableFirmware;

  hardware.xpadneo.enable = true;

  # see also https://github.com/TLATER/dotfiles/blob/e633196dca42d96f42f9aa9016fa8d307959232f/nixos-config/yui/nvidia.nix#L33
  # for wayland options
  # Listing here for redundancy:
  #   environment.variables = {
  #    # Necessary to correctly enable va-api (video codec hardware
  #    # acceleration). If this isn't set, the libvdpau backend will be
  #    # picked, and that one doesn't work with most things, including
  #    # Firefox.
  #    LIBVA_DRIVER_NAME = "nvidia";
  #    # Required to run the correct GBM backend for nvidia GPUs on wayland
  #    GBM_BACKEND = "nvidia-drm";
  #    # Apparently, without this nouveau may attempt to be used instead
  #    # (despite it being blacklisted)
  #    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
  #    # Hardware cursors are currently broken on nvidia
  #    WLR_NO_HARDWARE_CURSORS = "1";
  #
  #    # Required to use va-api it in Firefox. See
  #    # https://github.com/elFarto/nvidia-vaapi-driver/issues/96
  #    MOZ_DISABLE_RDD_SANDBOX = "1";
  #    # It appears that the normal rendering mode is broken on recent
  #    # nvidia drivers:
  #    # https://github.com/elFarto/nvidia-vaapi-driver/issues/213#issuecomment-1585584038
  #    NVD_BACKEND = "direct";
  #    # Required for firefox 98+, see:
  #    # https://github.com/elFarto/nvidia-vaapi-driver#firefox
  #    EGL_PLATFORM = "wayland";
  #  };

  programs.wrappedBinaries = {
    enable = true;
    binaries = {
      "firefox" = {
        cmdline = [
          "/usr/bin/env"
          "MOZ_ENABLE_WAYLAND=0"
          "LIBVA_DRIVER_NAME=nvidia"
          "MOZ_X11_EGL=1"
          "__EGL_VENDOR_LIBRARY_FILENAMES=${config.hardware.nvidia.package}/share/glvnd/egl_vendor.d/10_nvidia.json"
          "NVD_BACKEND=direct"
          "MOZ_DISABLE_RDD_SANDBOX=1"
          "${pkgs.firefox-bin}/bin/firefox"
        ];
      };
    };
  };
}
